version: '3'

services:
  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    restart: always
    volumes:
      - /data/overwall/https/certs:/certs
      - /data/overwall/v2ray/config.json:/etc/v2ray/config.json
    environment:
      VIRTUAL_PORT: "12345"
      HTTPS_METHOD: redirect
    env_file:
      - ./.env
    expose:
      - "12345"
    networks:
      proxy:

networks:
  proxy:
    external:
      name: nginx-proxy